// <auto-generated />
using System;
using Lims.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lims.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20260930233232_CompleteReferenceMaterials")]
    partial class CompleteReferenceMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lims.Domain.Authentication.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenFamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_token_family_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.HasIndex("ExpiresAt", "RevokedAt")
                        .HasDatabaseName("ix_auth_sessions_expiry_revocation");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Lims.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_auth_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_refresh_tokens_hash");

                    b.ToTable("auth_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Lims.Domain.Identity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("departamentos", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.UserPermissionGrant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("permiso_key");

                    b.HasKey("UserId", "Key");

                    b.ToTable("usuarios_permisos", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_by_user_id");

                    b.Property<decimal>("AvailableQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("CasNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cas_number");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("catalog_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<long?>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lot");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<decimal>("PresentationQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("presentation_quantity");

                    b.Property<decimal>("PurityPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("purity_percent");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<Guid?>("ReplacedByMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_material_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("StorageConditions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_conditions");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("storage_location");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_reference_materials_expiration_date");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_reference_materials_legacy_id")
                        .HasFilter("legacy_id IS NOT NULL");

                    b.HasIndex("Method")
                        .HasDatabaseName("ix_reference_materials_method");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_reference_materials_name");

                    b.HasIndex("ReplacedByMaterialId")
                        .HasDatabaseName("ix_reference_materials_replaced_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reference_materials_status");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CasNumber", "CatalogNumber")
                        .HasDatabaseName("ix_reference_materials_cas_catalog");

                    b.ToTable("reference_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_materials_available_quantity", "available_quantity >= 0 AND available_quantity <= presentation_quantity * package_count");

                            t.HasCheckConstraint("ck_reference_materials_dates", "expiration_date >= received_date");

                            t.HasCheckConstraint("ck_reference_materials_package_count", "package_count > 0");

                            t.HasCheckConstraint("ck_reference_materials_presentation_quantity", "presentation_quantity > 0");

                            t.HasCheckConstraint("ck_reference_materials_purity", "purity_percent > 0 AND purity_percent <= 100");

                            t.HasCheckConstraint("ck_reference_materials_replacement", "(status = 'Replaced' AND replaced_by_material_id IS NOT NULL) OR (status <> 'Replaced' AND replaced_by_material_id IS NULL)");

                            t.HasCheckConstraint("ck_reference_materials_status", "status IN ('Active','Depleted','Expired','Blocked','Replaced','Archived','Retired')");

                            t.HasCheckConstraint("ck_reference_materials_unit", "unit IN ('Microgram','Milligram','Gram','Kilogram','Milliliter','Liter')");
                        });
                });

            modelBuilder.Entity("Lims.Domain.Authentication.AuthSession", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Lims.Domain.Authentication.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Authentication.AuthSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.HasOne("Lims.Domain.Identity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lims.Domain.Identity.UserPermissionGrant", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceMaterial", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMaterial", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
