// <auto-generated />
using System;
using Lims.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lims.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    [Migration("20261007230730_AddIntermediatePreparations")]
    partial class AddIntermediatePreparations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("reference_intermediate_code_sequence");

            modelBuilder.HasSequence("reference_stock_code_sequence");

            modelBuilder.Entity("Lims.Domain.Authentication.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenFamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_token_family_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.HasIndex("ExpiresAt", "RevokedAt")
                        .HasDatabaseName("ix_auth_sessions_expiry_revocation");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Lims.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_auth_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_refresh_tokens_hash");

                    b.ToTable("auth_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Lims.Domain.Identity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("departamentos", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.Identity.UserPermissionGrant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("permiso_key");

                    b.HasKey("UserId", "Key");

                    b.ToTable("usuarios_permisos", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_reference_locations_name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_reference_locations_active_name");

                    b.ToTable("reference_locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_locations_name", "name = btrim(name) AND name <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Laboratorio"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Bodega"
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_by_user_id");

                    b.Property<decimal>("AvailableQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("CasNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cas_number");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("catalog_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lot");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer")
                        .HasColumnName("method_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<decimal>("PresentationQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("presentation_quantity");

                    b.Property<decimal>("PurityPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("purity_percent");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<Guid?>("ReplacedByMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_material_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("StorageTemperature")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("storage_temperature");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_reference_materials_expiration_date");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_reference_materials_location_id");

                    b.HasIndex("MethodId")
                        .HasDatabaseName("ix_reference_materials_method_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_reference_materials_name");

                    b.HasIndex("ReplacedByMaterialId")
                        .HasDatabaseName("ix_reference_materials_replaced_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reference_materials_status");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_reference_materials_unit_id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CasNumber", "CatalogNumber")
                        .HasDatabaseName("ix_reference_materials_cas_catalog");

                    b.ToTable("reference_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_materials_available_quantity", "available_quantity >= 0 AND available_quantity <= presentation_quantity * package_count");

                            t.HasCheckConstraint("ck_reference_materials_dates", "expiration_date >= received_date");

                            t.HasCheckConstraint("ck_reference_materials_package_count", "package_count > 0");

                            t.HasCheckConstraint("ck_reference_materials_presentation_quantity", "presentation_quantity > 0");

                            t.HasCheckConstraint("ck_reference_materials_purity", "purity_percent > 0 AND purity_percent <= 100");

                            t.HasCheckConstraint("ck_reference_materials_replacement", "(status = 'Replaced' AND replaced_by_material_id IS NOT NULL) OR (status <> 'Replaced' AND replaced_by_material_id IS NULL)");

                            t.HasCheckConstraint("ck_reference_materials_status", "status IN ('Active','Depleted','Expired','Blocked','Replaced','Archived','Retired')");
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_reference_methods_name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_reference_methods_active_name");

                    b.ToTable("reference_methods", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_methods_name", "name = btrim(name) AND name <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Azodyes"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "APEOs"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Disperse dyes"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Phtalatos"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "PCP"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "OPP"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Organotin"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "PAHs"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "SCCP/MCCP"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Retardantes de Flama"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "DMFA/DMFU"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "VOC"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "AEEA"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Bisphenol"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Halogenated"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Tiourea"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "PFC"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "COC"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Cresoles"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "UV"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Glicoles"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Metales"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "AMB"
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_reference_units_name");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("uq_reference_units_symbol");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_reference_units_active_name");

                    b.ToTable("reference_units", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_units_name", "name = btrim(name) AND name <> ''");

                            t.HasCheckConstraint("ck_reference_units_symbol", "symbol = btrim(symbol) AND symbol <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Mililitro",
                            Symbol = "mL"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gramo",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Miligramo",
                            Symbol = "mg"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Microgramo",
                            Symbol = "µg"
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferenceMaterialMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("balance_before");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PreparationId")
                        .HasColumnType("uuid")
                        .HasColumnName("preparation_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_material_id");

                    b.Property<Guid?>("SourcePreparationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_preparation_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ComponentId")
                        .IsUnique();

                    b.HasIndex("PreparationId")
                        .IsUnique()
                        .HasDatabaseName("ux_reference_material_movements_preparation")
                        .HasFilter("kind = 'StockConsumption'");

                    b.HasIndex("SourcePreparationId");

                    b.HasIndex("SourceMaterialId", "OccurredAt")
                        .HasDatabaseName("ix_reference_material_movements_source_time");

                    b.ToTable("reference_material_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_material_movements_balance", "quantity > 0 AND balance_before >= quantity AND balance_after >= 0 AND balance_after = balance_before - quantity");

                            t.HasCheckConstraint("ck_reference_material_movements_kind", "(kind = 'StockConsumption' AND source_material_id IS NOT NULL AND source_preparation_id IS NULL AND component_id IS NULL) OR (kind = 'IntermediateConsumption' AND source_material_id IS NULL AND source_preparation_id IS NOT NULL AND component_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferencePreparation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualConcentration")
                        .HasPrecision(40, 28)
                        .HasColumnType("numeric(40,28)")
                        .HasColumnName("actual_concentration");

                    b.Property<string>("ActualConcentrationUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actual_concentration_unit");

                    b.Property<decimal>("ActualWeight")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_weight");

                    b.Property<string>("ActualWeightUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actual_weight_unit");

                    b.Property<decimal>("AvailableVolume")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("available_volume");

                    b.Property<decimal>("CalculatedWeight")
                        .HasPrecision(40, 28)
                        .HasColumnType("numeric(40,28)")
                        .HasColumnName("calculated_weight");

                    b.Property<string>("CalculatedWeightUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("calculated_weight_unit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("ConcentrationUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("concentration_unit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DilutedPreparationId")
                        .HasColumnType("uuid")
                        .HasColumnName("diluted_preparation_id");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<decimal>("FinalVolume")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("final_volume");

                    b.Property<string>("FinalVolumeUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("final_volume_unit");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("formula");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<int?>("MethodId")
                        .HasColumnType("integer")
                        .HasColumnName("method_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PreparationDate")
                        .HasColumnType("date")
                        .HasColumnName("preparation_date");

                    b.Property<int>("PreparedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("prepared_by_user_id");

                    b.Property<decimal>("PurityPercentUsed")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("purity_percent_used");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results_json");

                    b.Property<string>("SourceBrand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_brand");

                    b.Property<string>("SourceCasNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_cas_number");

                    b.Property<string>("SourceCatalogNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_catalog_number");

                    b.Property<DateOnly>("SourceExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("source_expiration_date");

                    b.Property<string>("SourceLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_location");

                    b.Property<string>("SourceLot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_lot");

                    b.Property<Guid?>("SourceMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_material_id");

                    b.Property<string>("SourceMethod")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_method");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<decimal>("SourceTotalQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("source_total_quantity");

                    b.Property<string>("SourceUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_unit");

                    b.Property<Guid>("SourceVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("StorageTemperature")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_temperature");

                    b.Property<decimal>("TargetConcentration")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_concentration");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_reference_preparations_code");

                    b.HasIndex("DilutedPreparationId");

                    b.HasIndex("MethodId");

                    b.HasIndex("PreparationDate")
                        .HasDatabaseName("ix_reference_preparations_date");

                    b.HasIndex("PreparedByUserId")
                        .HasDatabaseName("ix_reference_preparations_actor");

                    b.HasIndex("SourceMaterialId")
                        .HasDatabaseName("ix_reference_preparations_source");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("reference_preparations", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_preparations_dates", "expiration_date >= preparation_date AND (kind <> 'Stock' OR preparation_date <= source_expiration_date) AND updated_at >= created_at");

                            t.HasCheckConstraint("ck_reference_preparations_identity", "length(trim(code)) > 0 AND length(trim(name)) > 0 AND length(request_fingerprint) = 64");

                            t.HasCheckConstraint("ck_reference_preparations_kind_status", "kind IN ('Stock','Intermedia') AND status = 'Active' AND (kind <> 'Stock' OR source_material_id IS NOT NULL) AND (kind <> 'Intermedia' OR (source_material_id IS NULL AND method_id IS NOT NULL))");

                            t.HasCheckConstraint("ck_reference_preparations_purity", "kind <> 'Stock' OR (purity_percent_used > 0 AND purity_percent_used <= 100)");

                            t.HasCheckConstraint("ck_reference_preparations_quantities", "final_volume > 0 AND available_volume >= 0 AND available_volume <= final_volume AND (kind <> 'Stock' OR (target_concentration > 0 AND actual_concentration > 0 AND calculated_weight > 0 AND actual_weight > 0 AND source_total_quantity >= actual_weight))");

                            t.HasCheckConstraint("ck_reference_preparations_units", "final_volume_unit IN ('mL','L') AND (kind <> 'Stock' OR (concentration_unit IN ('mg/L','g/L','µg/L','µg/mL') AND calculated_weight_unit = source_unit AND actual_weight_unit = source_unit AND actual_concentration_unit = concentration_unit AND source_unit IN ('g','mg','µg','μg','ug')))");
                        });
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferencePreparationComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("PreparationId")
                        .HasColumnType("uuid")
                        .HasColumnName("preparation_id");

                    b.Property<Guid>("SourcePreparationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_preparation_id");

                    b.Property<string>("SourceSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_snapshot_json");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("SourceVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version");

                    b.Property<decimal>("VolumeTaken")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("volume_taken");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("volume_unit");

                    b.HasKey("Id");

                    b.HasIndex("SourcePreparationId");

                    b.HasIndex("PreparationId", "Position")
                        .IsUnique();

                    b.HasIndex("PreparationId", "SourcePreparationId")
                        .IsUnique();

                    b.ToTable("reference_preparation_components", null, t =>
                        {
                            t.HasCheckConstraint("ck_reference_components_source", "preparation_id <> source_preparation_id AND source_type IN ('Stock','Intermedia')");

                            t.HasCheckConstraint("ck_reference_components_volume", "volume_taken > 0 AND volume_unit IN ('mL','L') AND position >= 0");
                        });
                });

            modelBuilder.Entity("Lims.Domain.Authentication.AuthSession", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Lims.Domain.Authentication.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Authentication.AuthSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.HasOne("Lims.Domain.Identity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lims.Domain.Identity.UserPermissionGrant", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.ReferenceMaterials.ReferenceMaterial", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMaterial", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Method");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferenceMaterialMovement", b =>
                {
                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparationComponent", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparation", "Preparation")
                        .WithMany()
                        .HasForeignKey("PreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMaterial", null)
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparation", null)
                        .WithMany()
                        .HasForeignKey("SourcePreparationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Preparation");
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferencePreparation", b =>
                {
                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparation", null)
                        .WithMany()
                        .HasForeignKey("DilutedPreparationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMethod", null)
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PreparedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferenceMaterials.ReferenceMaterial", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lims.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("Lims.Domain.ReferencePreparations.ReferencePreparationComponent", b =>
                {
                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparation", null)
                        .WithMany()
                        .HasForeignKey("PreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lims.Domain.ReferencePreparations.ReferencePreparation", null)
                        .WithMany()
                        .HasForeignKey("SourcePreparationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lims.Domain.Identity.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
