-- Materiales de Referencia: catálogos iniciales del nuevo LIMS.
-- Artefacto idempotente de referencia. No importa registros operativos de Trazalab.

BEGIN;

CREATE TABLE IF NOT EXISTS reference_methods (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_reference_methods_name CHECK (name = btrim(name) AND name <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_reference_methods_name
    ON reference_methods (lower(name));
CREATE INDEX IF NOT EXISTS ix_reference_methods_active_name
    ON reference_methods (is_active, name);

CREATE TABLE IF NOT EXISTS reference_units (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL,
    symbol varchar(16) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_reference_units_name CHECK (name = btrim(name) AND name <> ''),
    CONSTRAINT ck_reference_units_symbol CHECK (symbol = btrim(symbol) AND symbol <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_reference_units_name
    ON reference_units (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS uq_reference_units_symbol
    ON reference_units (lower(symbol));
CREATE INDEX IF NOT EXISTS ix_reference_units_active_name
    ON reference_units (is_active, name);

CREATE TABLE IF NOT EXISTS reference_locations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_reference_locations_name CHECK (name = btrim(name) AND name <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_reference_locations_name
    ON reference_locations (lower(name));
CREATE INDEX IF NOT EXISTS ix_reference_locations_active_name
    ON reference_locations (is_active, name);

INSERT INTO reference_methods (name, is_active)
SELECT seed.name, true
FROM (VALUES
    ('Azodyes'),
    ('APEOs'),
    ('Disperse dyes'),
    ('Phtalatos'),
    ('PCP'),
    ('OPP'),
    ('Organotin'),
    ('PAHs'),
    ('SCCP/MCCP'),
    ('Retardantes de Flama'),
    ('DMFA/DMFU'),
    ('VOC'),
    ('AEEA'),
    ('Bisphenol'),
    ('Halogenated'),
    ('Tiourea'),
    ('PFC'),
    ('COC'),
    ('Cresoles'),
    ('UV'),
    ('Glicoles'),
    ('Metales'),
    ('AMB')
) AS seed(name)
WHERE NOT EXISTS (
    SELECT 1 FROM reference_methods existing
    WHERE lower(existing.name) = lower(seed.name)
);

INSERT INTO reference_units (name, symbol, is_active)
SELECT seed.name, seed.symbol, true
FROM (VALUES
    ('Mililitro', 'mL'),
    ('Gramo', 'g'),
    ('Miligramo', 'mg'),
    ('Microgramo', 'µg')
) AS seed(name, symbol)
WHERE NOT EXISTS (
    SELECT 1 FROM reference_units existing
    WHERE lower(existing.name) = lower(seed.name)
       OR lower(existing.symbol) = lower(seed.symbol)
);

INSERT INTO reference_locations (name, is_active)
SELECT seed.name, true
FROM (VALUES
    ('Laboratorio'),
    ('Bodega')
) AS seed(name)
WHERE NOT EXISTS (
    SELECT 1 FROM reference_locations existing
    WHERE lower(existing.name) = lower(seed.name)
);

COMMIT;
